[project]
name = "memvid-test"
version = "0.1.0"
description = "A small test of memvid using Star Trek facts"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "memvid>=0.1.3",
    "openai>=1.93.3",
]
